services:
  essay-backend:
    build:
      context: .
    image: students-test-essay-backend:latest
    container_name: students-essay-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
